schema_version = "1.0.0"
id = "GeoMatch"
version = "1.1.0"
name = "Geo Match"
tagline = "Match geometry with different topology"
maintainer = "Blender Bob/Robert Rioux"
type = "add-on"
website = "https://github.com/riouxr/GeoMatch"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Robert Rioux"]